tongits: tongits.c tongits.h dyad.c dyad.h util.h config.h player.h card.h token.h lexer.h parser.h meld.h 
	gcc tongits.c dyad.c -o tongits -Wall -Wextra -g -std=c89

.PHONY: clean

clean:
	rm tongits
